name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

permissions:
  issues: write
  pull-requests: write
  actions: write
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base
          fetch-depth: 0

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          cd pr
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^src/.*\.md$\|^src/_includes/.*\.njk$\|^src/assets/.*\.css$' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (base)
        run: |
          cd base
          npm ci

      - name: Install dependencies (PR)
        run: |
          cd pr
          npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Puppeteer
        run: npm install puppeteer-core

      - name: Build sites and capture screenshots
        uses: actions/github-script@v7
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.files }}
        with:
          script: |
            const script = require('./pr/.github/workflows/preview/capture-screenshots.js')
            await script({ github, context, io })

      - name: Configure Git
        run: |
          cd pr
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push screenshots to Git
        id: push-screenshots
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./pr/.github/workflows/preview/push-screenshots.js')
            const commitHash = await script({ github, context, workingDir: 'pr' })
            core.setOutput('commit_hash', commitHash)

      - name: Post PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./pr/.github/workflows/preview/post-comment.js')
            await script({ github, context, commitHash: '${{ steps.push-screenshots.outputs.commit_hash }}' })
