name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

permissions:
  issues: write
  pull-requests: write
  actions: write
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base
          fetch-depth: 0

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          cd pr
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^src/.*\.md$\|^src/_includes/.*\.njk$\|^src/assets/.*\.css$' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (base)
        run: |
          cd base
          npm ci

      - name: Install dependencies (PR)
        run: |
          cd pr
          npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Puppeteer
        run: npm install puppeteer-core

      - name: Build sites and capture screenshots
        uses: actions/github-script@v7
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.files }}
        with:
          script: |
            const script = require('./.github/workflows/preview/capture-screenshots.js')
            await script({ github, context })

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: preview-screenshots
          path: screenshots/**/*.png
          if-no-files-found: error

      - name: Post PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/workflows/preview/post-comment.js')
            await script({ github, context })
